package ru.attendance.group;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.time.*;
import java.time.format.*;
import java.util.*;

public class MainActivity extends Activity {
    final int ACCENT=Color.rgb(18,168,137), ACCENT_SOFT=Color.rgb(232,247,243), INK=Color.rgb(23,33,43), MUTED=Color.rgb(115,128,140), BG=Color.rgb(247,249,250), LINE=Color.rgb(231,236,239), WHITE=Color.WHITE;
    android.content.SharedPreferences prefs; LocalDate date=LocalDate.now(); int tab=0, lesson=1; DayOfWeek scheduleDay=date.getDayOfWeek();
    ArrayList<String> students=new ArrayList<>();
    LinearLayout root, page, body; ScrollView scroll; int savedScrollY=0;
    int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
    @Override public void onCreate(Bundle b){super.onCreate(b); prefs=getSharedPreferences("attendance",0); loadStudents(); buildShell();}
    void loadStudents(){
        boolean initialized=prefs.getBoolean("students_initialized",false);
        String raw=prefs.getString("students","");
        if(!initialized){
            String[] a={"Басевская Яна","Вдовин Данил","Ведянина Анастасия","Галичина Алена","Корнеева Марина","Косых Елизавета","Крохина Полина","Медведева Ангелина","Филатов Кирилл","Шабанова Екатерина","Шаколова Виктория","Джумазода Зикрулло","Джумазода Кароматулло","Исхоки Исмоил","Рустамов Самандар","Хаитов Сиёвуш"};
            students.addAll(Arrays.asList(a)); saveStudents();
        } else if(!raw.isEmpty()) students.addAll(Arrays.asList(raw.split("\\n",-1)));
    }
    void saveStudents(){prefs.edit().putString("students",String.join("\n",students)).putBoolean("students_initialized",true).apply();}
    TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}
    GradientDrawable shape(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setBackground(shape(WHITE,20));l.setElevation(dp(1));return l;}
    LinearLayout.LayoutParams margins(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}
    TextView action(String s,int bg,int fg,float z){TextView t=tv(s,z,fg);t.setGravity(Gravity.CENTER);t.setBackground(shape(bg,14));t.setPadding(dp(8),0,dp(8),0);return t;}
    void buildShell(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);setContentView(root);renderPage();bottomNav();}
    void renderPage(){page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);scroll.setPadding(0,0,0,dp(16));body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);scroll.addView(body,new ScrollView.LayoutParams(-1,-2));page.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));root.addView(page,new LinearLayout.LayoutParams(-1,0,1));if(tab==0)home(body);else if(tab==1)schedule(body);else if(tab==2)stats(body);else more(body);}
    void bottomNav(){LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);nav.setPadding(dp(6),dp(5),dp(6),dp(5));nav.setBackgroundColor(WHITE);String[] a={"⌂\nГлавная","▦\nРасписание","◫\nСтатистика","•••\nЕщё"};for(int i=0;i<4;i++){final int x=i;TextView b=tv(a[i],12,i==tab?ACCENT:MUTED);b.setGravity(Gravity.CENTER);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setPadding(0,dp(4),0,dp(4));b.setOnClickListener(v->{savedScrollY=0;tab=x;buildShell();});nav.addView(b,new LinearLayout.LayoutParams(0,dp(54),1));}root.addView(nav,new LinearLayout.LayoutParams(-1,dp(64)));}
    void header(LinearLayout b,String title,String sub,boolean cal){LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(dp(20),dp(18),dp(20),dp(8));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(tv(title,26,INK));tx.addView(tv(sub,13,MUTED));h.addView(tx,new LinearLayout.LayoutParams(0,-2,1));if(cal){TextView c=action("▣",WHITE,INK,22);c.setOnClickListener(v->datePicker());h.addView(c,new LinearLayout.LayoutParams(dp(48),dp(48)));}b.addView(h);}
    void home(LinearLayout b){header(b,"ЦТБИД-266","Посещаемость группы",true);weekStrip(b);summary(b);lessonChips(b);subjectCard(b);TextView h=tv("Студенты",21,INK);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setPadding(dp(20),dp(4),dp(20),dp(9));b.addView(h);int mode=prefs.getInt("viewMode",1);TextView toggle=action(mode==0?"☷  Список":"▦  Сетка",ACCENT_SOFT,ACCENT,14);toggle.setOnClickListener(v->{prefs.edit().putInt("viewMode",mode==0?1:0).apply();savedScrollY=scroll==null?0:scroll.getScrollY();renderHomePreserve();});toggle.setPadding(dp(14),0,dp(14),0);b.addView(toggle,margins(20,0,20,10));if(mode==0)studentList(b);else studentGrid(b);actions(b);}
    void renderHomePreserve(){int y=scroll==null?0:scroll.getScrollY();root.removeAllViews();renderPage();bottomNav();scroll.post(()->scroll.scrollTo(0,y));}
    void weekStrip(LinearLayout b){LinearLayout row=new LinearLayout(this);row.setPadding(dp(14),dp(2),dp(14),dp(12));for(int i=-2;i<=4;i++){LocalDate d=date.plusDays(i);TextView x=tv(d.getDayOfWeek().getDisplayName(java.time.format.TextStyle.SHORT,new Locale("ru")).substring(0,2)+"\n"+d.getDayOfMonth(),12,d.equals(date)?WHITE:INK);x.setGravity(Gravity.CENTER);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setBackground(shape(d.equals(date)?ACCENT:WHITE,15));final LocalDate q=d;x.setOnClickListener(v->{date=q;savedScrollY=0;buildShell();});row.addView(x,new LinearLayout.LayoutParams(0,dp(52),1));}b.addView(row);}
    void summary(LinearLayout b){LinearLayout c=card();c.setPadding(dp(18),dp(15),dp(18),dp(15));c.addView(tv("Сегодня",14,MUTED));TextView big=tv(countGood(date,lesson)+" / "+students.size(),30,INK);big.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(big);c.addView(tv(countMarked(date,lesson)+" отмечено · "+formatDateLong(date),12,MUTED));b.addView(c,margins(20,0,20,14));}
    void lessonChips(LinearLayout b){LinearLayout row=new LinearLayout(this);row.setPadding(dp(20),0,dp(20),dp(13));for(int i=1;i<=4;i++){final int q=i;TextView x=action(i+" пара",i==lesson?INK:WHITE,i==lesson?WHITE:INK,13);x.setOnClickListener(v->{lesson=q;savedScrollY=scroll.getScrollY();renderHomePreserve();});row.addView(x,new LinearLayout.LayoutParams(0,dp(40),1));if(i<4)((LinearLayout.LayoutParams)x.getLayoutParams()).setMargins(0,0,dp(6),0);}b.addView(row);}
    void subjectCard(LinearLayout b){LinearLayout c=card();c.setPadding(dp(17),dp(14),dp(17),dp(14));String s=subject(date.getDayOfWeek().getValue(),lesson);c.addView(tv("ПАРА "+lesson+(s.isEmpty()?"":"  ·  "+s),15,INK));String tm=timeRange(date.getDayOfWeek().getValue(),lesson);c.addView(tv(tm.isEmpty()?"Время не задано":tm,12,MUTED));b.addView(c,margins(20,0,20,14));}
    void studentList(LinearLayout b){for(String n:students)addStudentRow(b,n,false);}
    void studentGrid(LinearLayout b){LinearLayout row=null;for(int i=0;i<students.size();i++){if(i%2==0){row=new LinearLayout(this);row.setPadding(dp(20),0,dp(20),0);b.addView(row,margins(0,0,0,7));}LinearLayout c=studentCard(students.get(i));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);if(i%2==0)p.setMargins(0,0,dp(4),0);else p.setMargins(dp(4),0,0,0);row.addView(c,p);}}
    LinearLayout studentCard(String n){LinearLayout c=card();c.setPadding(dp(9),dp(10),dp(9),dp(10));TextView num=tv("№ "+(students.indexOf(n)+1),11,MUTED);c.addView(num);TextView av=tv(initials(n),17,ACCENT);av.setGravity(Gravity.CENTER);av.setBackground(shape(ACCENT_SOFT,18));c.addView(av,new LinearLayout.LayoutParams(-1,dp(38)));TextView name=tv(shortName(n),12,INK);name.setGravity(Gravity.CENTER);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);name.setPadding(0,dp(5),0,dp(3));c.addView(name);TextView st=statusBadge(mark(date,lesson,n));st.setGravity(Gravity.CENTER);c.addView(st,new LinearLayout.LayoutParams(-1,dp(30)));c.setOnClickListener(v->cycleStudent(n));c.setOnLongClickListener(v->{studentMenu(n);return true;});return c;}
    void addStudentRow(LinearLayout b,String n,boolean dummy){LinearLayout c=card();c.setOrientation(LinearLayout.HORIZONTAL);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(11),dp(8),dp(11),dp(8));TextView no=tv(""+(students.indexOf(n)+1),12,MUTED);no.setGravity(Gravity.CENTER);c.addView(no,new LinearLayout.LayoutParams(dp(28),dp(42)));TextView av=tv(initials(n),13,ACCENT);av.setGravity(Gravity.CENTER);av.setBackground(shape(ACCENT_SOFT,22));c.addView(av,new LinearLayout.LayoutParams(dp(42),dp(42)));TextView name=tv(n,14,INK);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);name.setPadding(dp(10),0,dp(6),0);c.addView(name,new LinearLayout.LayoutParams(0,-2,1));TextView st=statusBadge(mark(date,lesson,n));st.setGravity(Gravity.CENTER);c.addView(st,new LinearLayout.LayoutParams(dp(44),dp(36)));c.setOnClickListener(v->cycleStudent(n));c.setOnLongClickListener(v->{studentMenu(n);return true;});b.addView(c,margins(20,0,20,7));}
    TextView statusBadge(String s){int bg=s.equals("✓")?ACCENT_SOFT:s.equals("×")?Color.rgb(252,235,235):s.equals("О")?Color.rgb(255,246,220):s.equals("У")?Color.rgb(232,240,252):Color.rgb(242,244,246);int fg=s.equals("✓")?ACCENT:s.equals("×")?Color.rgb(210,65,65):s.equals("О")?Color.rgb(180,125,0):s.equals("У")?Color.rgb(55,100,180):MUTED;return action(s,bg,fg,16);}
    void cycleStudent(String n){int y=scroll.getScrollY();next(date,lesson,n);renderHomePreserveAt(y);}
    void renderHomePreserveAt(int y){root.removeAllViews();renderPage();bottomNav();scroll.post(()->scroll.scrollTo(0,y));}
    void studentMenu(String n){new AlertDialog.Builder(this).setTitle(n).setItems(new String[]{"Удалить студента","Отмена"},(d,w)->{if(w==0)confirmDelete(n);}).show();}
    void confirmDelete(String n){new AlertDialog.Builder(this).setTitle("Удалить студента?").setMessage("Удалить «"+n+"» из группы? История отметок этого студента тоже будет удалена.").setNegativeButton("Отмена",null).setPositiveButton("Удалить",(d,w)->{SharedPreferences.Editor ed=prefs.edit();for(String k:prefs.getAll().keySet())if(k.startsWith("mark/")&&k.endsWith("/"+n))ed.remove(k);students.remove(n);ed.putString("students",String.join("\n",students)).putBoolean("students_initialized",true).apply();buildShell();}).show();}
    String initials(String n){String[] p=n.trim().split("\\s+");return p.length>=2?(p[0].substring(0,1)+p[1].substring(0,1)).toUpperCase():n.substring(0,Math.min(2,n.length())).toUpperCase();}
    String shortName(String n){String[] p=n.split(" ");return p.length>1?p[0]+"\n"+p[1]:n;}
    void actions(LinearLayout b){LinearLayout r=new LinearLayout(this);r.setPadding(dp(20),dp(5),dp(20),dp(20));TextView all=action("Все были",INK,WHITE,14);all.setOnClickListener(v->{for(String n:students)setMark(date,lesson,n,"P");int y=scroll.getScrollY();renderHomePreserveAt(y);});TextView ex=action("Экспорт",ACCENT,WHITE,14);ex.setOnClickListener(v->export());r.addView(all,new LinearLayout.LayoutParams(0,dp(46),1));((LinearLayout.LayoutParams)all.getLayoutParams()).setMargins(0,0,dp(7),0);r.addView(ex,new LinearLayout.LayoutParams(0,dp(46),1));b.addView(r);}
    void schedule(LinearLayout b){header(b,"Расписание","Предметы и время занятий",false);LinearLayout days=new LinearLayout(this);days.setPadding(dp(14),0,dp(14),dp(13));for(DayOfWeek d:DayOfWeek.values()){final DayOfWeek q=d;TextView x=action(d.getDisplayName(java.time.format.TextStyle.SHORT,new Locale("ru")),q==scheduleDay?INK:WHITE,q==scheduleDay?WHITE:INK,11);x.setOnClickListener(v->{scheduleDay=q;savedScrollY=0;buildShell();});days.addView(x,new LinearLayout.LayoutParams(0,dp(40),1));}b.addView(days);for(int i=1;i<=4;i++)scheduleRow(b,i);}
    void scheduleRow(LinearLayout b,int i){LinearLayout c=card();c.setPadding(dp(15),dp(13),dp(15),dp(13));LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView n=tv(i+" пара",17,INK);n.setTypeface(Typeface.DEFAULT,Typeface.BOLD);head.addView(n,new LinearLayout.LayoutParams(0,-2,1));TextView save=action("Сохранить",ACCENT_SOFT,ACCENT,13);head.addView(save,new LinearLayout.LayoutParams(dp(102),dp(38)));c.addView(head);EditText e=new EditText(this);e.setSingleLine(true);e.setTextSize(15);e.setTextColor(INK);e.setHintTextColor(MUTED);e.setHint("Название предмета");e.setBackground(shape(BG,14));e.setPadding(dp(13),0,dp(13),0);e.setText(subject(scheduleDay.getValue(),i));c.addView(e,new LinearLayout.LayoutParams(-1,dp(50)));LinearLayout times=new LinearLayout(this);times.setGravity(Gravity.CENTER_VERTICAL);EditText from=timeEdit("Начало",timeFrom(scheduleDay.getValue(),i));EditText to=timeEdit("Конец",timeTo(scheduleDay.getValue(),i));times.addView(from,new LinearLayout.LayoutParams(0,dp(48),1));((LinearLayout.LayoutParams)from.getLayoutParams()).setMargins(0,dp(7),dp(4),0);times.addView(to,new LinearLayout.LayoutParams(0,dp(48),1));((LinearLayout.LayoutParams)to.getLayoutParams()).setMargins(dp(4),dp(7),0,0);c.addView(times);save.setOnClickListener(v->{prefs.edit().putString("sub"+scheduleDay.getValue()+"-"+i,e.getText().toString().trim()).putString("from"+scheduleDay.getValue()+"-"+i,from.getText().toString().trim()).putString("to"+scheduleDay.getValue()+"-"+i,to.getText().toString().trim()).apply();Toast.makeText(this,"Пара сохранена",Toast.LENGTH_SHORT).show();});b.addView(c,margins(20,0,20,10));}
    EditText timeEdit(String hint,String val){EditText e=new EditText(this);e.setSingleLine(true);e.setTextSize(14);e.setTextColor(INK);e.setHintTextColor(MUTED);e.setHint(hint);e.setInputType(android.text.InputType.TYPE_CLASS_DATETIME|android.text.InputType.TYPE_DATETIME_VARIATION_TIME);e.setText(val);e.setGravity(Gravity.CENTER);e.setBackground(shape(BG,14));return e;}
    String timeFrom(int d,int l){return prefs.getString("from"+d+"-"+l,"");} String timeTo(int d,int l){return prefs.getString("to"+d+"-"+l,"");}
    String timeRange(int d,int l){String a=timeFrom(d,l),b=timeTo(d,l);return a.isEmpty()&&b.isEmpty()?"":(a.isEmpty()?"до "+b:b.isEmpty()?"с "+a:a+"–"+b);}
    void stats(LinearLayout b){header(b,"Статистика","Общая картина посещаемости",true);int marked=0,good=0;LocalDate start=date.withDayOfMonth(1),end=date.withDayOfMonth(date.lengthOfMonth());for(LocalDate d=start;!d.isAfter(end);d=d.plusDays(1))for(int l=1;l<=4;l++)for(String n:students){String s=mark(d,l,n);if(!s.equals("—")){marked++;if(s.equals("✓")||s.equals("О"))good++;}}int pct=marked==0?0:good*100/marked;LinearLayout hero=card();hero.setBackground(shape(INK,24));hero.setPadding(dp(20),dp(19),dp(20),dp(19));hero.addView(tv("Посещаемость за "+formatMonth(date),14,Color.LTGRAY));TextView big=tv(pct+"%",42,WHITE);big.setTypeface(Typeface.DEFAULT,Typeface.BOLD);big.setPadding(0,dp(3),0,0);hero.addView(big);hero.addView(tv(marked+" отметок · "+good+" посещений",13,Color.LTGRAY));b.addView(hero,margins(20,0,20,18));TextView h=tv("По студентам",22,INK);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setPadding(dp(20),0,dp(20),dp(9));b.addView(h);for(String n:students){int m=0,g=0;for(LocalDate d=start;!d.isAfter(end);d=d.plusDays(1))for(int l=1;l<=4;l++){String s=mark(d,l,n);if(!s.equals("—")){m++;if(s.equals("✓")||s.equals("О"))g++;}}LinearLayout c=card();c.setPadding(dp(15),dp(12),dp(15),dp(12));LinearLayout line=new LinearLayout(this);line.setGravity(Gravity.CENTER_VERTICAL);TextView name=tv(n,14,INK);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);line.addView(name,new LinearLayout.LayoutParams(0,-2,1));TextView percent=tv((m==0?0:g*100/m)+"%",15,ACCENT);percent.setTypeface(Typeface.DEFAULT,Typeface.BOLD);line.addView(percent);c.addView(line);c.addView(tv(m==0?"Нет отметок":"Отмечено "+m+" · присутствовал "+g,12,MUTED));b.addView(c,margins(20,0,20,7));}}
    void more(LinearLayout b){header(b,"Ещё","Группа и данные",false);TextView add=action("＋  Добавить студента",INK,WHITE,18);add.setGravity(Gravity.CENTER_VERTICAL);add.setPadding(dp(17),0,0,0);add.setOnClickListener(v->addStudent());b.addView(add,margins(20,0,20,9));TextView ex=action("↗  Экспорт в Excel",ACCENT,WHITE,18);ex.setGravity(Gravity.CENTER_VERTICAL);ex.setPadding(dp(17),0,0,0);ex.setOnClickListener(v->export());b.addView(ex,margins(20,0,20,18));LinearLayout info=card();info.setPadding(dp(17),dp(15),dp(17),dp(15));info.addView(tv("Состав группы",14,MUTED));TextView count=tv(students.size()+" студентов",20,INK);count.setTypeface(Typeface.DEFAULT,Typeface.BOLD);count.setPadding(0,dp(3),0,0);info.addView(count);b.addView(info,margins(20,0,20,12));TextView hint=tv("Чтобы удалить студента, зажми его карточку в списке или сетке.",13,MUTED);hint.setPadding(dp(20),dp(4),dp(20),0);b.addView(hint);}
    void addStudent(){final EditText input=new EditText(this);input.setHint("Фамилия Имя");input.setSingleLine(true);input.setPadding(dp(12),0,dp(12),0);input.setBackground(shape(BG,14));LinearLayout wrap=new LinearLayout(this);wrap.setPadding(dp(20),0,dp(20),0);wrap.addView(input,new LinearLayout.LayoutParams(-1,dp(52)));new AlertDialog.Builder(this).setTitle("Новый студент").setView(wrap).setNegativeButton("Отмена",null).setPositiveButton("Добавить",(d,w)->{String s=input.getText().toString().trim();if(!s.isEmpty()){students.add(s);saveStudents();buildShell();}}).show();}
    void datePicker(){new DatePickerDialog(this,(v,y,m,day)->{date=LocalDate.of(y,m+1,day);savedScrollY=0;buildShell();},date.getYear(),date.getMonthValue()-1,date.getDayOfMonth()).show();}
    String formatDateLong(LocalDate d){return d.format(DateTimeFormatter.ofPattern("d MMMM yyyy",new Locale("ru")));}String formatMonth(LocalDate d){return d.format(DateTimeFormatter.ofPattern("LLLL yyyy",new Locale("ru")));}
    String subject(int d,int l){return prefs.getString("sub"+d+"-"+l,"");}String key(LocalDate d,int l,String n){return "mark/"+d+"/"+l+"/"+n;}String mark(LocalDate d,int l,String n){String s=prefs.getString(key(d,l,n),"");return s.equals("P")?"✓":s.equals("A")?"×":s.equals("L")?"О":s.equals("E")?"У":"—";}void setMark(LocalDate d,int l,String n,String s){prefs.edit().putString(key(d,l,n),s).apply();}void next(LocalDate d,int l,String n){String s=prefs.getString(key(d,l,n),"");String q=s.equals("")?"P":s.equals("P")?"A":s.equals("A")?"L":s.equals("L")?"E":"";setMark(d,l,n,q);}int countMarked(LocalDate d,int l){int c=0;for(String n:students)if(!mark(d,l,n).equals("—"))c++;return c;}int countGood(LocalDate d,int l){int c=0;for(String n:students){String s=mark(d,l,n);if(s.equals("✓")||s.equals("О"))c++;}return c;}
    void export(){String name="Посещаемость_ЦТБИД-266_"+date.getYear()+".xls";Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/vnd.ms-excel");i.putExtra(Intent.EXTRA_TITLE,name);startActivityForResult(i,42);}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode!=42||resultCode!=RESULT_OK||data==null)return;Uri uri=data.getData();StringBuilder h=new StringBuilder("<html><head><meta charset='UTF-8'></head><body><table border='1'><tr><th>Дата</th><th>Пара</th><th>Время</th><th>Предмет</th><th>Студент</th><th>Статус</th></tr>");LocalDate a=LocalDate.of(date.getYear(),1,1),bb=LocalDate.of(date.getYear(),12,31);for(LocalDate d=a;!d.isAfter(bb);d=d.plusDays(1))for(int l=1;l<=4;l++)for(String n:students){String s=mark(d,l,n);if(!s.equals("—")){String st=s.equals("✓")?"Был":s.equals("×")?"Не был":s.equals("О")?"Опоздал":"Уважительная причина";h.append("<tr><td>").append(d).append("</td><td>").append(l).append("</td><td>").append(escape(timeRange(d.getDayOfWeek().getValue(),l))).append("</td><td>").append(escape(subject(d.getDayOfWeek().getValue(),l))).append("</td><td>").append(escape(n)).append("</td><td>").append(st).append("</td></tr>");}}h.append("</table></body></html>");try(OutputStream out=getContentResolver().openOutputStream(uri)){out.write(h.toString().getBytes("UTF-8"));Toast.makeText(this,"Excel-файл сохранён",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"Не удалось сохранить файл",Toast.LENGTH_LONG).show();}}
    String escape(String s){return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;");}
}
