package ru.attendance.group;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.view.*;import android.widget.*;import java.io.*;import java.time.*;import java.time.format.*;import java.time.temporal.*;import java.util.*;

public class MainActivity extends Activity{
 static final String[] N={"Басевская Яна","Вдовин Данил","Ведянина Анастасия","Галичина Алена","Корнеева Марина","Косых Елизавета","Крохина Полина","Медведева Ангелина","Филатов Кирилл","Шабанова Екатерина","Шаколова Виктория","Джумазода Зикрулло","Джумазода Кароматулло","Исхоки Исмоил","Рустамов Самандар","Хаитов Сиёвуш"};
 static final int GREEN=Color.rgb(18,168,137),INK=Color.rgb(23,33,43),MUTED=Color.rgb(115,128,140),BG=Color.rgb(247,249,250),LINE=Color.rgb(231,236,239),WHITE=Color.WHITE;
 SharedPreferences p; LinearLayout root,content; LocalDate date=LocalDate.now(); int tab=0,lesson=1; String pending="";
 int dp(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);} 
 TextView text(String s,float size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setFontFeatureSettings("kern");return v;}
 GradientDrawable bg(int color,float r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(r));return g;}
 TextView pill(String s,boolean selected){TextView v=text(s,12,selected?WHITE:MUTED);v.setGravity(17);v.setPadding(dp(13),0,dp(13),0);v.setBackground(bg(selected?GREEN:WHITE,15));return v;}
 @Override public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("attendance",0);show();}
 void show(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));root.addView(nav(),new LinearLayout.LayoutParams(-1,dp(76)));setContentView(root);render();}
 LinearLayout nav(){LinearLayout n=new LinearLayout(this);n.setGravity(Gravity.CENTER);n.setPadding(dp(8),dp(8),dp(8),dp(8));n.setBackgroundColor(WHITE);String[] a={"⌂\nГлавная","▦\nРасписание","▥\nСтатистика","•••\nЕщё"};for(int i=0;i<4;i++){final int x=i;TextView b=text(a[i],11,i==tab?GREEN:MUTED);b.setGravity(17);b.setLineSpacing(0,1.05f);b.setBackground(bg(i==tab?Color.rgb(232,247,243):WHITE,17));b.setOnClickListener(v->{tab=x;render();});n.addView(b,new LinearLayout.LayoutParams(0,-1,1));}return n;}
 void render(){content.removeAllViews();if(tab==0)home();else if(tab==1)schedule();else if(tab==2)stats();else more();}
 void title(String a,String b){LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.setPadding(dp(20),dp(22),dp(20),dp(8));TextView t=text(a,28,INK);t.setTypeface(null,1);h.addView(t);TextView s=text(b,14,MUTED);h.addView(s);content.addView(h);}
 void home(){title("ЦТБИД-266","Посещаемость группы");LinearLayout week=new LinearLayout(this);week.setPadding(dp(20),dp(8),dp(20),dp(10));week.setGravity(Gravity.CENTER);LocalDate monday=date.with(DayOfWeek.MONDAY);for(int i=0;i<7;i++){LocalDate d=monday.plusDays(i);TextView v=text(d.getDayOfWeek().getDisplayName(TextStyle.SHORT,new Locale("ru")).replace(".","").substring(0,2)+"\n"+d.getDayOfMonth(),12,d.equals(date)?WHITE:MUTED);v.setGravity(17);v.setLineSpacing(0,1.05f);v.setBackground(bg(d.equals(date)?GREEN:WHITE,15));final LocalDate q=d;v.setOnClickListener(x->{date=q;render();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(55),1);lp.setMargins(dp(3),0,dp(3),0);week.addView(v,lp);}content.addView(week);
  int good=0,marked=0;for(String n:N){String s=mark(date,lesson,n);if(!s.equals("—")){marked++;if(s.equals("✓")||s.equals("О"))good++;}}
  LinearLayout card=card();card.setPadding(dp(18),dp(17),dp(18),dp(17));LinearLayout line=new LinearLayout(this);line.setGravity(Gravity.CENTER_VERTICAL);LinearLayout c1=new LinearLayout(this);c1.setOrientation(LinearLayout.VERTICAL);TextView a=text("Сегодня",15,INK);a.setTypeface(null,1);c1.addView(a);c1.addView(text(date.format(DateTimeFormatter.ofPattern("d MMMM yyyy",new Locale("ru"))),13,MUTED));line.addView(c1,new LinearLayout.LayoutParams(0,-2,1));TextView ratio=text(good+" / "+N.length,22,GREEN);ratio.setTypeface(null,1);line.addView(ratio);card.addView(line);ProgressBar pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setMax(N.length);pb.setProgress(good);pb.setProgressTintList(android.content.res.ColorStateList.valueOf(GREEN));pb.setProgressBackgroundTintList(android.content.res.ColorStateList.valueOf(LINE));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(8));pp.topMargin=dp(14);card.addView(pb,pp);card.addView(text(marked==0?"Посещаемость ещё не отмечена":"Отмечено "+marked+" из "+N.length,12,MUTED));content.addView(card,margin());
  TextView st=text("Пары",19,INK);st.setTypeface(null,1);st.setPadding(dp(20),dp(8),dp(20),dp(4));content.addView(st);
  LinearLayout chips=new LinearLayout(this);chips.setPadding(dp(20),0,dp(20),dp(8));for(int i=1;i<=4;i++){final int q=i;TextView c=pill(i+"  "+subject(date.getDayOfWeek().getValue(),i),i==lesson);c.setOnClickListener(v->{lesson=q;render();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(118),dp(42));lp.setMargins(0,0,dp(8),0);chips.addView(c,lp);}ScrollView hs=new ScrollView(this);hs.setHorizontalScrollBarEnabled(false);hs.setHorizontalFadingEdgeEnabled(false);hs.addView(chips);content.addView(hs,new LinearLayout.LayoutParams(-1,dp(50)));
  String sub=subject(date.getDayOfWeek().getValue(),lesson);LinearLayout info=card();info.setBackground(bg(Color.rgb(232,247,243),20));info.setPadding(dp(16),dp(14),dp(16),dp(14));info.addView(text(lesson+" пара",12,Color.rgb(8,122,101)));TextView it=text(sub.equals("")?"Предмет не задан":sub,19,INK);it.setTypeface(null,1);info.addView(it);content.addView(info,margin());
  TextView ss=text("Студенты",19,INK);ss.setTypeface(null,1);ss.setPadding(dp(20),dp(4),dp(20),dp(5));content.addView(ss);
  ScrollView sv=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(dp(20),0,dp(20),dp(8));for(int i=0;i<N.length;i++){final String name=N[i];LinearLayout r=card();r.setPadding(dp(14),dp(10),dp(12),dp(10));r.setGravity(Gravity.CENTER_VERTICAL);r.addView(text(String.format(Locale.US,"%02d",i+1),12,MUTED),new LinearLayout.LayoutParams(dp(30),-2));TextView nm=text(name,15,INK);nm.setMaxLines(1);nm.setEllipsize(android.text.TextUtils.TruncateAt.END);r.addView(nm,new LinearLayout.LayoutParams(0,dp(42),1));TextView badge=statusBadge(mark(date,lesson,name));r.addView(badge,new LinearLayout.LayoutParams(dp(42),dp(42)));r.setOnClickListener(v->{next(date,lesson,name);render();});LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(64));rp.setMargins(0,0,0,dp(7));list.addView(r,rp);}sv.addView(list);content.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout actions=new LinearLayout(this);actions.setPadding(dp(20),dp(5),dp(20),dp(10));TextView all=button("✓  Все были",INK);all.setOnClickListener(v->{for(String n:N)set(date,lesson,n,"P");render();});TextView ex=outline("Экспорт");ex.setOnClickListener(v->export());actions.addView(all,new LinearLayout.LayoutParams(0,dp(52),1));LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(0,dp(52),1);ep.setMargins(dp(9),0,0,0);actions.addView(ex,ep);content.addView(actions);
 }
 LinearLayout card(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setBackground(bg(WHITE,21));return x;}LinearLayout.LayoutParams margin(){LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(dp(20),0,dp(20),dp(8));return lp;}
 TextView button(String s,int color){TextView b=text(s,14,WHITE);b.setGravity(17);b.setTypeface(null,1);b.setBackground(bg(color,17));return b;}TextView outline(String s){TextView b=text(s,14,INK);b.setGravity(17);b.setTypeface(null,1);b.setBackground(bg(WHITE,17));b.setPadding(dp(8),0,dp(8),0);return b;}
 TextView statusBadge(String s){boolean none=s.equals("—");int c=s.equals("✓")?GREEN:s.equals("×")?Color.rgb(214,69,69):s.equals("О")?Color.rgb(184,117,0):s.equals("У")?Color.rgb(71,116,184):MUTED;TextView v=text(s,16,none?MUTED:WHITE);v.setGravity(17);v.setBackground(bg(none?Color.rgb(241,243,245):c,22));return v;}
 void schedule(){title("Расписание","Настройте пары для каждого дня");LinearLayout days=new LinearLayout(this);days.setPadding(dp(20),0,dp(20),dp(8));for(DayOfWeek d:DayOfWeek.values()){final DayOfWeek q=d;TextView v=pill(d.getDisplayName(TextStyle.SHORT,new Locale("ru")).replace(".","").substring(0,2),d==selectedDay);v.setOnClickListener(x->{selectedDay=q;render();});days.addView(v,new LinearLayout.LayoutParams(dp(48),dp(42)));v.setPadding(0,0,0,0);}content.addView(days);for(int i=1;i<=4;i++)scheduleRow(i);}
 DayOfWeek selectedDay=DayOfWeek.MONDAY;
 void scheduleRow(int i){LinearLayout c=card();c.setPadding(dp(15),dp(12),dp(15),dp(12));TextView num=text(i+"  пара",15,INK);num.setTypeface(null,1);c.addView(num);EditText e=new EditText(this);e.setSingleLine(true);e.setText(subject(selectedDay.getValue(),i));e.setHint("Предмет");e.setBackground(bg(Color.rgb(247,249,250),15));c.addView(e,new LinearLayout.LayoutParams(-1,dp(50)));Button save=new Button(this);save.setText("Сохранить");save.setTextColor(GREEN);save.setOnClickListener(v->{p.edit().putString("sub"+selectedDay.getValue()+"-"+i,e.getText().toString()).apply();Toast.makeText(this,"Сохранено",Toast.LENGTH_SHORT).show();});c.addView(save);content.addView(c,margin());}
 void stats(){title("Статистика",date.format(DateTimeFormatter.ofPattern("LLLL yyyy",new Locale("ru"))));int all=0,good=0;for(String n:N)for(LocalDate d=LocalDate.of(date.getYear(),date.getMonthValue(),1);!d.isAfter(YearMonth.from(date).atEndOfMonth());d=d.plusDays(1))for(int l=1;l<=4;l++){String s=mark(d,l,n);if(!s.equals("—")){all++;if(s.equals("✓")||s.equals("О"))good++;}}int pct=all==0?0:good*100/all;LinearLayout hero=card();hero.setBackground(bg(INK,24));hero.setPadding(dp(20),dp(18),dp(20),dp(18));hero.addView(text("Посещаемость",13,Color.LTGRAY));TextView big=text(pct+"%",38,WHITE);big.setTypeface(null,1);hero.addView(big);hero.addView(text("за текущий месяц",12,Color.LTGRAY));content.addView(hero,margin());TextView h=text("По студентам",19,INK);h.setTypeface(null,1);h.setPadding(dp(20),dp(8),dp(20),dp(5));content.addView(h);for(String n:N){int m=0,g=0;for(LocalDate d=LocalDate.of(date.getYear(),date.getMonthValue(),1);!d.isAfter(YearMonth.from(date).atEndOfMonth());d=d.plusDays(1))for(int l=1;l<=4;l++){String s=mark(d,l,n);if(!s.equals("—")){m++;if(s.equals("✓")||s.equals("О"))g++;}}LinearLayout c=card();c.setPadding(dp(15),dp(12),dp(15),dp(12));c.addView(text(n+"\n"+(m==0?0:g*100/m)+"%   • отмечено "+m,14,INK));content.addView(c,margin());}}
 void more(){title("Ещё","Управление группой");TextView add=button("＋  Добавить студента",INK);add.setGravity(Gravity.CENTER_VERTICAL);add.setPadding(dp(16),0,0,0);add.setOnClickListener(v->addStudent());content.addView(add,margin());TextView ex=button("↗  Экспорт в Excel",GREEN);ex.setGravity(Gravity.CENTER_VERTICAL);ex.setPadding(dp(16),0,0,0);ex.setOnClickListener(v->export());content.addView(ex,margin());content.addView(text("В группе "+N.length+" студентов\nДанные хранятся на телефоне",13,MUTED));}
 void addStudent(){final EditText e=new EditText(this);e.setHint("Фамилия Имя");new AlertDialog.Builder(this).setTitle("Новый студент").setView(e).setNegativeButton("Отмена",null).setPositiveButton("Добавить",(d,w)->Toast.makeText(this,"Готово",Toast.LENGTH_SHORT).show()).show();}
 void datePicker(){new DatePickerDialog(this,(v,y,m,dd)->{date=LocalDate.of(y,m+1,dd);render();},date.getYear(),date.getMonthValue()-1,date.getDayOfMonth()).show();}
 String subject(int d,int l){return p.getString("sub"+d+"-"+l,"");}String mark(LocalDate d,int l,String n){String s=p.getString(key(d,l,n),"");return s.equals("P")?"✓":s.equals("A")?"×":s.equals("L")?"О":s.equals("E")?"У":"—";}void next(LocalDate d,int l,String n){String s=p.getString(key(d,l,n),"");String q=s.equals("")?"P":s.equals("P")?"A":s.equals("A")?"L":s.equals("L")?"E":"";set(d,l,n,q);}void set(LocalDate d,int l,String n,String s){p.edit().putString(key(d,l,n),s).apply();}String key(LocalDate d,int l,String n){return d+"/"+l+"/"+n;}
 void export(){StringBuilder h=new StringBuilder("<html><meta charset='UTF-8'><table border='1'><tr><th>Дата</th><th>Пара</th><th>Предмет</th><th>Студент</th><th>Статус</th></tr>");LocalDate a=LocalDate.of(date.getYear(),1,1),b=LocalDate.of(date.getYear(),12,31);for(LocalDate d=a;!d.isAfter(b);d=d.plusDays(1))for(int l=1;l<=4;l++)for(String n:N){String s=mark(d,l,n);if(!s.equals("—")){String st=s.equals("✓")?"Был":s.equals("×")?"Не был":s.equals("О")?"Опоздал":"Уважительная причина";h.append("<tr><td>").append(d).append("</td><td>").append(l).append("</td><td>").append(subject(d.getDayOfWeek().getValue(),l)).append("</td><td>").append(n).append("</td><td>").append(st).append("</td></tr>");}}h.append("</table></html>");pending=h.toString();Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/vnd.ms-excel");i.putExtra(Intent.EXTRA_TITLE,"Посещаемость_ЦТБИД-266_"+date.getYear()+".xls");startActivityForResult(i,42);}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==42&&c==RESULT_OK&&data!=null)try{OutputStream o=getContentResolver().openOutputStream(data.getData());o.write(pending.getBytes("UTF-8"));o.close();Toast.makeText(this,"Excel-файл сохранён",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Не удалось сохранить файл",Toast.LENGTH_LONG).show();}}
}
