package ru.attendance.group;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.time.*;
import java.time.format.*;
import java.util.*;

public class MainActivity extends Activity {
    final int ACCENT=Color.rgb(18,168,137), ACCENT_SOFT=Color.rgb(232,247,243), INK=Color.rgb(23,33,43), MUTED=Color.rgb(115,128,140), BG=Color.rgb(247,249,250), WHITE=Color.WHITE;
    SharedPreferences prefs; LocalDate date=LocalDate.now(); int tab=0, lesson=1; DayOfWeek scheduleDay=date.getDayOfWeek();
    ArrayList<String> students=new ArrayList<>();
    LinearLayout root,body; ScrollView scroll; TextView summaryBig,summarySmall; HashMap<String,TextView> visibleBadges=new HashMap<>();
    int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
    @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("attendance",0);loadStudents();buildShell();}
    void loadStudents(){boolean init=prefs.getBoolean("students_initialized",false);String raw=prefs.getString("students","");if(!init){String[] a={"Басевская Яна","Вдовин Данил","Ведянина Анастасия","Галичина Алена","Корнеева Марина","Косых Елизавета","Крохина Полина","Медведева Ангелина","Филатов Кирилл","Шабанова Екатерина","Шаколова Виктория","Джумазода Зикрулло","Джумазода Кароматулло","Исхоки Исмоил","Рустамов Самандар","Хаитов Сиёвуш"};students.addAll(Arrays.asList(a));saveStudents();}else if(!raw.isEmpty())students.addAll(Arrays.asList(raw.split("\\n",-1)));}
    void saveStudents(){prefs.edit().putString("students",String.join("\n",students)).putBoolean("students_initialized",true).apply();}
    TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}
    GradientDrawable shape(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setBackground(shape(WHITE,20));l.setElevation(dp(1));return l;}
    LinearLayout.LayoutParams margins(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}
    TextView action(String s,int bg,int fg,float z){TextView t=tv(s,z,fg);t.setGravity(Gravity.CENTER);t.setBackground(shape(bg,14));t.setPadding(dp(8),0,dp(8),0);return t;}
    void buildShell(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);setContentView(root);renderPage();bottomNav();}
    void renderPage(){visibleBadges.clear();LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);scroll.setPadding(0,0,0,dp(16));body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);scroll.addView(body,new ScrollView.LayoutParams(-1,-2));page.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));root.addView(page,new LinearLayout.LayoutParams(-1,0,1));if(tab==0)home(body);else if(tab==1)schedule(body);else if(tab==2)stats(body);else more(body);}
    void bottomNav(){LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);nav.setPadding(dp(6),dp(5),dp(6),dp(5));nav.setBackgroundColor(WHITE);String[] a={"⌂\nГлавная","▦\nРасписание","◫\nСтатистика","•••\nЕщё"};for(int i=0;i<4;i++){final int x=i;TextView b=tv(a[i],12,i==tab?ACCENT:MUTED);b.setGravity(Gravity.CENTER);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setPadding(0,dp(4),0,dp(4));b.setOnClickListener(v->{tab=x;buildShell();});nav.addView(b,new LinearLayout.LayoutParams(0,dp(54),1));}root.addView(nav,new LinearLayout.LayoutParams(-1,dp(64)));}
    void header(LinearLayout b,String title,String sub,boolean cal){LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(dp(20),dp(18),dp(20),dp(8));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(tv(title,26,INK));tx.addView(tv(sub,13,MUTED));h.addView(tx,new LinearLayout.LayoutParams(0,-2,1));if(cal){TextView c=action("▣",WHITE,INK,22);c.setOnClickListener(v->datePicker());h.addView(c,new LinearLayout.LayoutParams(dp(48),dp(48)));}b.addView(h);}
    void home(LinearLayout b){header(b,"ЦТБИД-266","Посещаемость группы",true);weekStrip(b);summary(b);lessonChips(b);subjectCard(b);TextView h=tv("Студенты",21,INK);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setPadding(dp(20),dp(4),dp(20),dp(9));b.addView(h);int mode=prefs.getInt("viewMode",1);TextView toggle=action(mode==0?"☷  Список":"▦  Сетка",ACCENT_SOFT,ACCENT,14);toggle.setOnClickListener(v->{prefs.edit().putInt("viewMode",mode==0?1:0).apply();int y=scroll.getScrollY();buildShell();scroll.post(()->scroll.scrollTo(0,y));});b.addView(toggle,margins(20,0,20,10));if(mode==0)studentList(b);else studentGrid(b);actions(b);}
    void weekStrip(LinearLayout b){LinearLayout row=new LinearLayout(this);row.setPadding(dp(14),dp(2),dp(14),dp(12));for(int i=-2;i<=4;i++){LocalDate d=date.plusDays(i);TextView x=tv(d.getDayOfWeek().getDisplayName(TextStyle.SHORT,new Locale("ru")).substring(0,2)+"\n"+d.getDayOfMonth(),12,d.equals(date)?WHITE:INK);x.setGravity(Gravity.CENTER);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setBackground(shape(d.equals(date)?ACCENT:WHITE,15));final LocalDate q=d;x.setOnClickListener(v->{date=q;buildShell();});row.addView(x,new LinearLayout.LayoutParams(0,dp(52),1));}b.addView(row);}
    void summary(LinearLayout b){LinearLayout c=card();c.setPadding(dp(18),dp(15),dp(18),dp(15));c.addView(tv("Сегодня",14,MUTED));summaryBig=tv(countGood(date,lesson)+" / "+students.size(),30,INK);summaryBig.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(summaryBig);summarySmall=tv(countMarked(date,lesson)+" отмечено · "+formatDateLong(date),12,MUTED);c.addView(summarySmall);b.addView(c,margins(20,0,20,14));}
    void refreshSummary(){if(summaryBig!=null)summaryBig.setText(countGood(date,lesson)+" / "+students.size());if(summarySmall!=null)summarySmall.setText(countMarked(date,lesson)+" отмечено · "+formatDateLong(date));}
    void lessonChips(LinearLayout b){LinearLayout row=new LinearLayout(this);row.setPadding(dp(20),0,dp(20),dp(13));for(int i=1;i<=4;i++){final int q=i;TextView x=action(i+" пара",i==lesson?INK:WHITE,i==lesson?WHITE:INK,13);x.setOnClickListener(v->{lesson=q;buildShell();});row.addView(x,new LinearLayout.LayoutParams(0,dp(40),1));if(i<4)((LinearLayout.LayoutParams)x.getLayoutParams()).setMargins(0,0,dp(6),0);}b.addView(row);}
    void subjectCard(LinearLayout b){LinearLayout c=card();c.setPadding(dp(17),dp(14),dp(17),dp(14));String s=subject(date.getDayOfWeek().getValue(),lesson);c.addView(tv("ПАРА "+lesson+(s.isEmpty()?"":"  ·  "+s),15,INK));String tm=timeRange(date.getDayOfWeek().getValue(),lesson);c.addView(tv(tm.isEmpty()?"Время не задано":tm,12,MUTED));b.addView(c,margins(20,0,20,14));}
    void studentList(LinearLayout b){for(String n:students)addStudentRow(b,n);}
    void studentGrid(LinearLayout b){LinearLayout row=null;for(int i=0;i<students.size();i++){if(i%2==0){row=new LinearLayout(this);row.setPadding(dp(20),0,dp(20),0);b.addView(row,margins(0,0,0,7));}LinearLayout c=studentCard(students.get(i));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);if(i%2==0)p.setMargins(0,0,dp(4),0);else p.setMargins(dp(4),0,0,0);row.addView(c,p);}}
    LinearLayout studentCard(String n){LinearLayout c=card();c.setPadding(dp(9),dp(10),dp(9),dp(10));TextView num=tv("№ "+(students.indexOf(n)+1),11,MUTED);c.addView(num);TextView av=tv(initials(n),17,ACCENT);av.setGravity(Gravity.CENTER);av.setBackground(shape(ACCENT_SOFT,18));c.addView(av,new LinearLayout.LayoutParams(-1,dp(38)));TextView name=tv(shortName(n),12,INK);name.setGravity(Gravity.CENTER);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);name.setPadding(0,dp(5),0,dp(3));c.addView(name);TextView st=statusBadge(mark(date,lesson,n));st.setGravity(Gravity.CENTER);c.addView(st,new LinearLayout.LayoutParams(-1,dp(30)));visibleBadges.put(n,st);attachAttendance(c,n);return c;}
    void addStudentRow(LinearLayout b,String n){LinearLayout c=card();c.setOrientation(LinearLayout.HORIZONTAL);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(11),dp(8),dp(11),dp(8));TextView no=tv(""+(students.indexOf(n)+1),12,MUTED);no.setGravity(Gravity.CENTER);c.addView(no,new LinearLayout.LayoutParams(dp(28),dp(42)));TextView av=tv(initials(n),13,ACCENT);av.setGravity(Gravity.CENTER);av.setBackground(shape(ACCENT_SOFT,22));c.addView(av,new LinearLayout.LayoutParams(dp(42),dp(42)));TextView name=tv(n,14,INK);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);name.setPadding(dp(10),0,dp(6),0);c.addView(name,new LinearLayout.LayoutParams(0,-2,1));TextView st=statusBadge(mark(date,lesson,n));st.setGravity(Gravity.CENTER);c.addView(st,new LinearLayout.LayoutParams(dp(44),dp(36)));visibleBadges.put(n,st);attachAttendance(c,n);b.addView(c,margins(20,0,20,7));}
    void attachAttendance(View v,String n){v.setOnClickListener(x->cycleStudent(n));v.setOnLongClickListener(x->{quickMark(n);return true;});}
    TextView statusBadge(String s){int bg=s.equals("✓")?ACCENT_SOFT:s.equals("×")?Color.rgb(252,235,235):s.equals("О")?Color.rgb(255,246,220):s.equals("У")?Color.rgb(232,240,252):Color.rgb(242,244,246);int fg=s.equals("✓")?ACCENT:s.equals("×")?Color.rgb(210,65,65):s.equals("О")?Color.rgb(180,125,0):s.equals("У")?Color.rgb(55,100,180):MUTED;return action(s,bg,fg,16);}
    void cycleStudent(String n){String v=next(date,lesson,n);updateBadge(n,v);}
    void updateBadge(String n,String v){TextView st=visibleBadges.get(n);if(st!=null){TextView fresh=statusBadge(v);st.setText(fresh.getText());st.setTextColor(fresh.getTextColors());st.setBackground(fresh.getBackground());}refreshSummary();}
    void quickMark(String n){String[] labels={"✓  Присутствует","×  Отсутствует","О  Опоздал","У  Уважительная причина","—  Сбросить отметку"};String[] values={"P","A","L","E",""};new AlertDialog.Builder(this).setTitle(n).setItems(labels,(d,w)->{setMark(date,lesson,n,values[w]);updateBadge(n,values[w].equals("P")?"✓":values[w].equals("A")?"×":values[w].equals("L")?"О":values[w].equals("E")?"У":"—");}).show();}
    void actions(LinearLayout b){LinearLayout r=new LinearLayout(this);r.setPadding(dp(20),dp(5),dp(20),dp(20));TextView all=action("Все были",INK,WHITE,14);all.setOnClickListener(v->{for(String n:students){setMark(date,lesson,n,"P");updateBadge(n,"✓");}});TextView ex=action("Экспорт",ACCENT,WHITE,14);ex.setOnClickListener(v->export());r.addView(all,new LinearLayout.LayoutParams(0,dp(46),1));((LinearLayout.LayoutParams)all.getLayoutParams()).setMargins(0,0,dp(7),0);r.addView(ex,new LinearLayout.LayoutParams(0,dp(46),1));b.addView(r);}
    void schedule(LinearLayout b){header(b,"Расписание","Предметы и время занятий",false);LinearLayout days=new LinearLayout(this);days.setPadding(dp(14),0,dp(14),dp(13));for(DayOfWeek d:DayOfWeek.values()){final DayOfWeek q=d;TextView x=action(d.getDisplayName(TextStyle.SHORT,new Locale("ru")),q==scheduleDay?INK:WHITE,q==scheduleDay?WHITE:INK,11);x.setOnClickListener(v->{scheduleDay=q;buildShell();});days.addView(x,new LinearLayout.LayoutParams(0,dp(40),1));}b.addView(days);for(int i=1;i<=4;i++)scheduleRow(b,i);}
    EditText timeEdit(String hint,String val){EditText e=new EditText(this);e.setSingleLine(true);e.setTextSize(14);e.setTextColor(INK);e.setHintTextColor(MUTED);e.setHint(hint);e.setText(val);e.setGravity(Gravity.CENTER);e.setBackground(shape(BG,14));return e;}
    void scheduleRow(LinearLayout b,int i){LinearLayout c=card();c.setPadding(dp(15),dp(13),dp(15),dp(13));LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView n=tv(i+" пара",17,INK);n.setTypeface(Typeface.DEFAULT,Typeface.BOLD);head.addView(n,new LinearLayout.LayoutParams(0,-2,1));TextView save=action("Сохранить",ACCENT_SOFT,ACCENT,13);head.addView(save,new LinearLayout.LayoutParams(dp(102),dp(38)));c.addView(head);EditText e=new EditText(this);e.setSingleLine(true);e.setTextSize(15);e.setTextColor(INK);e.setHintTextColor(MUTED);e.setHint("Название предмета");e.setBackground(shape(BG,14));e.setPadding(dp(13),0,dp(13),0);e.setText(subject(scheduleDay.getValue(),i));c.addView(e,new LinearLayout.LayoutParams(-1,dp(50)));LinearLayout times=new LinearLayout(this);times.setGravity(Gravity.CENTER_VERTICAL);EditText from=timeEdit("Начало",timeFrom(scheduleDay.getValue(),i));EditText to=timeEdit("Конец",timeTo(scheduleDay.getValue(),i));times.addView(from,new LinearLayout.LayoutParams(0,dp(48),1));((LinearLayout.LayoutParams)from.getLayoutParams()).setMargins(0,dp(7),dp(4),0);times.addView(to,new LinearLayout.LayoutParams(0,dp(48),1));((LinearLayout.LayoutParams)to.getLayoutParams()).setMargins(dp(4),dp(7),0,0);c.addView(times);save.setOnClickListener(v->{prefs.edit().putString("sub"+scheduleDay.getValue()+"-"+i,e.getText().toString().trim()).putString("from"+scheduleDay.getValue()+"-"+i,from.getText().toString().trim()).putString("to"+scheduleDay.getValue()+"-"+i,to.getText().toString().trim()).apply();Toast.makeText(this,"Пара сохранена",Toast.LENGTH_SHORT).show();});b.addView(c,margins(20,0,20,10));}
    void stats(LinearLayout b){header(b,"Статистика","Посещаемость группы",false);for(String n:students){int total=0,good=0;for(int k=1;k<=4;k++){for(String key:prefs.getAll().keySet()){if(key.startsWith("mark/")&&key.endsWith("/"+n+"/"+k)){total++;Object o=prefs.getAll().get(key);if("P".equals(o))good++;}}}LinearLayout c=card();c.setOrientation(LinearLayout.HORIZONTAL);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(14),dp(10),dp(14),dp(10));TextView name=tv(n,14,INK);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(name,new LinearLayout.LayoutParams(0,-2,1));c.addView(tv(total==0?"Нет данных":good+" / "+total,14,ACCENT));b.addView(c,margins(20,0,20,7));}}
    void more(LinearLayout b){header(b,"Ещё","Настройки группы",false);TextView add=action("＋  Добавить студента",ACCENT,WHITE,15);add.setOnClickListener(v->addStudent());b.addView(add,margins(20,4,20,10));TextView help=tv("Как отмечать\n\n• Нажми на карточку — обычная отметка переключается по кругу.\n• Зажми карточку — сразу выбери нужный статус.\n• Долгое нажатие на карточку также позволяет удалить студента.\n\nДанные хранятся на телефоне. Экспорт доступен на главном экране.",14,INK);help.setPadding(dp(20),dp(14),dp(20),dp(20));b.addView(help);}
    void addStudent(){EditText e=new EditText(this);e.setHint("Фамилия Имя");e.setSingleLine(true);e.setPadding(dp(14),0,dp(14),0);new AlertDialog.Builder(this).setTitle("Добавить студента").setView(e).setNegativeButton("Отмена",null).setPositiveButton("Добавить",(d,w)->{String n=e.getText().toString().trim();if(!n.isEmpty()&&!students.contains(n)){students.add(n);saveStudents();Toast.makeText(this,"Студент добавлен",Toast.LENGTH_SHORT).show();buildShell();}}).show();}
    void studentMenu(String n){new AlertDialog.Builder(this).setTitle(n).setItems(new String[]{"Удалить студента","Отмена"},(d,w)->{if(w==0)confirmDelete(n);}).show();}
    void confirmDelete(String n){new AlertDialog.Builder(this).setTitle("Удалить студента?").setMessage("Удалить «"+n+"» из группы? История отметок этого студента тоже будет удалена.").setNegativeButton("Отмена",null).setPositiveButton("Удалить",(d,w)->{SharedPreferences.Editor ed=prefs.edit();for(String k:prefs.getAll().keySet())if(k.startsWith("mark/")&&k.endsWith("/"+n))ed.remove(k);students.remove(n);ed.putString("students",String.join("\n",students)).putBoolean("students_initialized",true).apply();buildShell();}).show();}
    String initials(String n){String[] p=n.trim().split("\\s+");return p.length>=2?(p[0].substring(0,1)+p[1].substring(0,1)).toUpperCase():n.substring(0,Math.min(2,n.length())).toUpperCase();}
    String shortName(String n){String[] p=n.trim().split("\\s+");return p.length>1?p[0]+"\n"+p[1]:n;}
    void datePicker(){DatePickerDialog d=new DatePickerDialog(this,(v,y,m,day)->{date=LocalDate.of(y,m+1,day);buildShell();},date.getYear(),date.getMonthValue()-1,date.getDayOfMonth());d.show();}
    String key(LocalDate d,int l,String n){return "mark/"+d+"/"+l+"/"+n;}
    String mark(LocalDate d,int l,String n){String v=prefs.getString(key(d,l,n),"");return v.equals("P")?"✓":v.equals("A")?"×":v.equals("L")?"О":v.equals("E")?"У":"—";}
    void setMark(LocalDate d,int l,String n,String v){SharedPreferences.Editor e=prefs.edit();if(v==null||v.isEmpty())e.remove(key(d,l,n));else e.putString(key(d,l,n),v);e.apply();}
    String next(LocalDate d,int l,String n){String cur=prefs.getString(key(d,l,n),"");String v=cur.isEmpty()?"P":cur.equals("P")?"A":cur.equals("A")?"L":cur.equals("L")?"E":"";setMark(d,l,n,v);return v.equals("P")?"✓":v.equals("A")?"×":v.equals("L")?"О":v.equals("E")?"У":"—";}
    int countMarked(LocalDate d,int l){int c=0;for(String n:students)if(!mark(d,l,n).equals("—"))c++;return c;}
    int countGood(LocalDate d,int l){int c=0;for(String n:students)if(mark(d,l,n).equals("✓"))c++;return c;}
    String formatDateLong(LocalDate d){return d.format(DateTimeFormatter.ofPattern("d MMMM yyyy",new Locale("ru")));}
    String subject(int day,int l){return prefs.getString("sub"+day+"-"+l,"");}
    String timeFrom(int day,int l){return prefs.getString("from"+day+"-"+l,"");}
    String timeTo(int day,int l){return prefs.getString("to"+day+"-"+l,"");}
    String timeRange(int day,int l){String a=timeFrom(day,l),b=timeTo(day,l);if(a.isEmpty()&&b.isEmpty())return "";return a+(a.isEmpty()||b.isEmpty()?"":" — ")+b;}
    void export(){try{StringBuilder s=new StringBuilder("Дата\tПара\tВремя\tПредмет");for(String n:students)s.append("\t").append(n);s.append("\n");LocalDate start=date.withDayOfMonth(1),end=date.withDayOfMonth(date.lengthOfMonth());for(LocalDate d=start;!d.isAfter(end);d=d.plusDays(1))for(int l=1;l<=4;l++){boolean any=false;for(String n:students)if(!mark(d,l,n).equals("—")){any=true;break;}if(!any)continue;s.append(d).append("\t").append(l).append("\t").append(timeRange(d.getDayOfWeek().getValue(),l)).append("\t").append(subject(d.getDayOfWeek().getValue(),l));for(String n:students)s.append("\t").append(mark(d,l,n));s.append("\n");}File f=new File(getCacheDir(),"Посещаемость_ЦТБИД-266.xls");try(FileOutputStream o=new FileOutputStream(f)){o.write(s.toString().getBytes("UTF-16LE"));}Intent i=new Intent(Intent.ACTION_SEND);i.setType("application/vnd.ms-excel");i.putExtra(Intent.EXTRA_STREAM,Uri.fromFile(f));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);try{startActivity(Intent.createChooser(i,"Экспорт посещаемости"));}catch(Exception e){Toast.makeText(this,"Не найдено приложение для отправки файла",Toast.LENGTH_LONG).show();}}catch(Exception e){Toast.makeText(this,"Ошибка экспорта",Toast.LENGTH_LONG).show();}}
}
